// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ilactakipsistem.Data;

#nullable disable

namespace ilactakipsistem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408112551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ilactakipsistem.Models.DosageSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DosageAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("DosageSchedules");
                });

            modelBuilder.Entity("ilactakipsistem.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriticalStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("ilactakipsistem.Models.UsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("UsageLogs");
                });

            modelBuilder.Entity("ilactakipsistem.Models.DosageSchedule", b =>
                {
                    b.HasOne("ilactakipsistem.Models.Medicine", "Medicine")
                        .WithMany("DosageSchedules")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ilactakipsistem.Models.UsageLog", b =>
                {
                    b.HasOne("ilactakipsistem.Models.Medicine", "Medicine")
                        .WithMany("UsageLogs")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ilactakipsistem.Models.Medicine", b =>
                {
                    b.Navigation("DosageSchedules");

                    b.Navigation("UsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
